services:

  anchr:
    build: ./
    container_name: anchr
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - anchr_data:/app/data
    env_file: .env
    environment:
      - ANCHR_DB_HOST=mongo
      - ANCHR_DB_PORT=27017
      - LISTEN_ADDR=0.0.0.0
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    volumes:
      - anchr_db_data:/data/db
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ANCHR_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${ANCHR_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${ANCHR_DB_NAME}
      - DB_USER=${ANCHR_DB_USER}
      - DB_PASSWORD=${ANCHR_DB_PASSWORD}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=http://0.0.0.0/prometheus'
      - '--web.route-prefix=/'
    depends_on:
      - anchr

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    restart: unless-stopped
    depends_on:
      - anchr

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - anchr
      - prometheus
      - grafana

volumes:
  anchr_data:
  anchr_db_data:
  prometheus_data:
  grafana_data:


