global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    # Reuse the global interval for this job
    scrape_interval: 15s 
    static_configs:
      # 'prometheus' here is the service name defined in docker-compose.yml
      - targets: ['prometheus:9090'] 
